name = "bookly-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "staging"

[[d1_databases]]
binding = "DB"
database_name = "bookly-db-staging"
database_id = "3ac0e526-2d04-4d2f-ae83-df41512ddccb"
migrations_dir = "src/db/migrations"
