name = "bookly-api-prod"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "bookly-db-prod"
database_id = "664aa451-359d-4564-bc15-b81ccd40ea0b"
migrations_dir = "src/db/migrations"
